# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Fipe_11_18' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'

  # Pods for Fipe_11_18

  target 'Fipe_11_18Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Fipe_11_18UITests' do
    # Pods for testing
  end

end
